var database = [
  
    {
        id: "1",
        songs: "如此可爱",
        name: "梁芝芝",
        src: "music/如此可爱.mp3",
        alltime: "04:36",
        photo: "images/rz.jpg",
        lyrics: [{time: "00:00", lyric: " "},
            {time: "00:01", lyric: "如此可爱"},
            {time: "00:02", lyric: " "},
            {time: "00:03", lyric: "演唱：梁芝芝"},
        
            {time: "00:08", lyric: ""},
            {time: "00:18", lyric: "是命中注定 "},
            {time: "00:21", lyric: "或万中选一"},
            {time: "00:25", lyric: "就是如此 肯定"},
            {time: "00:27", lyric: "是缘分注定"},
            {time: "00:32", lyric: "是百里挑一"},
            {time: "00:35", lyric: "就是如此 笃定"},
            {time: "00:37", lyric: "我们的爱 如此澎湃 滚滚而来"},
            {time: "00:40", lyric: "我们的爱 如此多彩 多么可爱"},
            {time: "00:46", lyric: "我们的爱 如此澎湃 滚滚而来"},
            {time: "00:47", lyric: "我们的爱 如此多彩 多么可爱"},
            {time: "00:55", lyric: "是命中注定"},
            {time: "00:58", lyric: "或万中选一"},
            {time: "01:01", lyric: "就是如此 肯定"},
            {time: "01:04", lyric: "是缘分注定"},
            {time: "01:10", lyric: "是百里挑一"},
            {time: "01:16", lyric: "就是如此 笃定"},
            {time: "01:16", lyric: "我们的爱 如此澎湃 滚滚而来"},
            {time: "01:19", lyric: "我们的爱 如此多彩 多么可爱"},
            {time: "01:24", lyric: "我们的爱 如此澎湃 滚滚而来"},
            {time: "01:28", lyric: "我们的爱 如此多彩 多么可爱"},
        ]
    },
    {
        id: "2", songs: "洒脱", name: "梁芝芝", src: "music/洒脱.mp3", alltime: "05:54", photo: "images/lyj.jpg", lyrics: [
        {time: "00:02", lyric: "洒脱"},
        {time: "00:13", lyric: "梁芝芝"},
        {time: "00:30", lyric: "我也不再要求什么"},
        {time: "00:31", lyric: "可不可以别忘了我"},
        {time: "00:39", lyric: "你如此冷漠"},
        {time: "00:46", lyric: "我不敢再说"},
        {time: "01:02", lyric: "好像多一句就逃脱"},
        {time: "01:10", lyric: "这样若即若离你才洒脱"},
        {time: "01:17", lyric: "一切都变了"},
        {time: "01:28", lyric: "你不是我的"},
        {time: "01:33", lyric: "我也不再要求什么"},
        {time: "01:40", lyric: "可不可以别忘了我"},
        {time: "01:48", lyric: "你如此冷漠"},
        {time: "01:56", lyric: "我不敢再说"},
        {time: "02:02", lyric: "好像多一句就逃脱"},
        {time: "02:02", lyric: "这样若即若离你才洒脱"},
       
    ]
    },
    {
        id: "3",
        songs: "逝去的爱情",
        name: "梁芝芝",
        src: "music/失去的爱情.mp3",
        alltime: "04:00",
        photo: "images/cyx.jpg",
        lyrics: [{time: "00:01", lyric: "逝去的爱情"},
            {time: "00:04", lyric: "梁芝芝"},
            {time: "00:06", lyric: "《认了吧》"},
            {time: "00:11", lyric: "你等待着我的消息"},
            {time: "00:16", lyric: "我想说却又不忍心"},
            {time: "00:18", lyric: "其实我早已有了心仪"},
            {time: "00:23", lyric: "所有刺激剩下疲乏的痛 你消失在我的生命"},
            {time: "00:29", lyric: "如何告诉你这个消息"},
            {time: "00:37", lyric: "害怕你这样放弃自己"},
            {time: "00:44", lyric: "虽然你已渐渐远去"},
            {time: "00:47", lyric: "却依然留存美好回忆"},
            {time: "00:55", lyric: "说声对不起"},
            {time: "00:59", lyric: "我也不是故意"},
            {time: "01:03", lyric: "真的不想拖累你"},
            {time: "01:06", lyric: "未来还有更好的人"},
            {time: "01:10", lyric: "你等待着我的消息"},
            {time: "01:14", lyric: "我想说却又不忍心"},
            {time: "01:29", lyric: "其实我早已有了心仪"},
            {time: "01:33", lyric: "你消失在我的生命"},
            {time: "01:37", lyric: "如何告诉你这个消息"},
            {time: "01:44", lyric: "害怕你这样放弃自己"},
            {time: "01:52", lyric: "虽然你已渐渐远去"},
            {time: "01:59", lyric: "却依然留存美好回忆"},
            {time: "02:03", lyric: "说声对不起"},
            {time: "02:06", lyric: "我也不是故意"},
            {time: "02:11", lyric: "真的不想拖累你"},
            {time: "02:14", lyric: "未来还有更好的人"},
           ]
    },
    {
        id: "4",
        songs: "誓言",
        name: "梁芝芝",
        src: "music/誓言.mp3",
        alltime: "03:53",
        photo: "images/yzw.jpg",
        lyrics: [{time: "00:01", lyric: "誓言"},
            {time: "00:02", lyric: "作词：黄婷 作曲：木村充利"},
            {time: "00:04", lyric: "演唱：梁芝芝"},
            {time: "00:07", lyric: "誓言有什么用"},
            {time: "00:25", lyric: "说再多都听不够"},
            {time: "00:31", lyric: "最重要是你可以"},
            {time: "00:36", lyric: "在我身边多么久"},
            {time: "00:42", lyric: "告诉我 你有多难受"},
            {time: "00:46", lyric: "告诉我 你爱我不够"},
            {time: "00:54", lyric: "誓言有什么用"},
            {time: "00:57", lyric: "说再多都听不够"},
            {time: "00:59", lyric: "最重要是你可以"},
            {time: "01:03", lyric: "在我身边多么久"},
            {time: "01:08", lyric: "告诉我 你有多难受"},
            {time: "01:09", lyric: "告诉我 你爱我不够"},
            {time: "01:14", lyric: "如果到头来都没有收获"},
            {time: "01:20", lyric: "誓言就算再多也是空"},
           ]
    },
    {
        id: "5", songs: "守护孤独", name: "梁芝芝", src: "music/守护孤独.mp3", alltime: "04.06", photo: "images/zxy.jpg", lyrics: [
        {time: "00:01", lyric: "守护孤独"},
        {time: "00:01", lyric: "作词 :姚若龙　作曲 :戚小恋"},
        {time: "00:02", lyric: "演唱：梁芝芝"},
        {time: "00:03", lyric: ""},
        {time: "00:23", lyric: "每一分秒钟 期待着的梦"},
        {time: "00:27", lyric: "靠近的温柔 关心的问候"},
        {time: "00:32", lyric: "时针在转动 我仍在枯坐"},
        {time: "00:34", lyric: "终于才明白 独单是始终"},
        {time: "00:35", lyric: "你始终 是我最初的冲动"},
        {time: "00:38", lyric: "我始终 是你逃避的借口"},
        {time: "00:41", lyric: "你始终 藏在我心最里头"},
        {time: "00:46", lyric: "我始终 没能走进你的梦"},
        {time: "00:50", lyric: "每一分秒钟 期待着的梦"},
        {time: "00:52", lyric: "靠近的温柔 关心的问候"},
        {time: "00:54", lyric: "时针在转动 我仍在枯坐"},
        {time: "00:59", lyric: "终于才明白 独单是始终"},
        {time: "01:03", lyric: "你始终 是我最初的冲动"},
        {time: "01:07", lyric: "我始终 是你逃避的借口"},
        {time: "01:11", lyric: "你始终 藏在我心最里头"},
        {time: "01:16", lyric: "我始终 没能走进你的梦"},
      
    ]
    },
    {
        id: "6",
        songs: "受伤的心",
        name: "梁芝芝",
        src: "music/受伤的心.mp3",
        alltime: "03:54",
        photo: "../img/chun3.png",
        lyrics: [
            {time: '00:00',lyric:'我的心啊 在你那呢' },
            {time: "00:04", lyric: "放了好久 已经生锈"},
            {time: "00:08", lyric: "你还给我 原封不动"},
            {time: "00:12", lyric: "一阵冰凉 浑身是伤"},
            {time: "00:16", lyric: "我太软弱这一点我始终承认"},
            {time: "00:20", lyric: "不敢违抗你的任何否认"},
            {time: "00:24", lyric: "也许男人都不喜欢逆来顺受"},
            {time: "00:28", lyric: "有些挑战才能爱的深沉"},
            {time: "00:32", lyric: "我的心啊 在你那呢"},
            {time: "00:37", lyric: "放了好久 已经生锈"},
            {time: "00:41", lyric: "你还给我 原封不动"},
            {time: "00:45", lyric: "一阵冰凉 浑身是伤"},
            {time: "00:49", lyric: "我太软弱这一点我始终承认"},
            {time: "00:53", lyric: "不敢违抗你的任何否认"},
            {time: "00:57", lyric: "也许男人都不喜欢逆来顺受"},
        ]
    },
    {
        id: "7",
        songs: "说什么呢",
        name: "梁芝芝",
        src: "music/说什么呢.mp3",
        alltime: "03:53",
        photo: "../img/zhiyao.png",
        lyrics: [
         
            {time: "00:03", lyric: ""},
            {time: "00:04", lyric: "挽回无补于事"},
            {time: "00:08", lyric: "你苦着脸的样子"},
            {time: "00:12", lyric: "还能再多说什么"},
            {time: "00:16", lyric: "一句都已经太多"},
            {time: "00:20", lyric: "不想再这样下去"},
            {time: "00:24", lyric: "留给你这空房子"},
            {time: "00:28", lyric: "让你一人玩手指"},
            {time: "00:32", lyric: "寂寞会把你吞噬"},
            {time: "00:37", lyric: "挽回无补于事"},
            {time: "00:41", lyric: "你苦着脸的样子"},
            {time: "00:45", lyric: "还能再多说什么"},
            {time: "00:49", lyric: "一句都已经太多"},
            {time: "00:53", lyric: "不想再这样下去"},
            {time: "00:57", lyric: "留给你这空房子"},
            {time: "01:01", lyric: "让你一人玩手指"},
            {time: "01:05", lyric: "寂寞会把你吞噬"},
          
        ]
    },
    {
        id: "8",
        songs: "梦中的婚礼(钢琴曲)",
        name: "Richard Clayderman",
        src: "music/梦中的婚礼.mp3",
        alltime: "02:42",
        photo: "../img/chun1.png",
        lyrics: [
            {time: "00:04", lyric: "你是我的小太阳"},
            {time: "00:06", lyric: "时时刻刻在身边发光"},
            {time: "00:11", lyric: "给我温暖和光亮"},
            {time: "00:16", lyric: "给我明天的希望"},
            {time: "00:18", lyric: "你是我的小太阳"},
            {time: "00:23", lyric: "每天唤醒我起床"},
            {time: "00:29", lyric: "给我无限的力量"},
            {time: "00:37", lyric: "给我未知的远方"},
            {time: "00:44", lyric: "小太阳 我的小太阳"},
            {time: "00:47", lyric: "多想时时刻刻在你的身旁"},
            {time: "00:55", lyric: "为你做一切可能的事"},
            {time: "00:59", lyric: "然后看着你可爱的笑"},
            {time: "01:03", lyric: "你是我的小太阳"},
            {time: "01:06", lyric: "时时刻刻在身边发光"},
            {time: "01:10", lyric: "给我温暖和光亮"},
            {time: "01:14", lyric: "给我明天的希望"},
            {time: "01:29", lyric: "你是我的小太阳"},
            {time: "01:33", lyric: "每天唤醒我起床"},
            {time: "01:37", lyric: "给我无限的力量"},
            {time: "01:44", lyric: "给我未知的远方"},
            {time: "01:52", lyric: "小太阳 我的小太阳"},
            {time: "01:59", lyric: "多想时时刻刻在你的身旁"},
            {time: "02:03", lyric: "为你做一切可能的事"},
            {time: "02:06", lyric: "然后看着你可爱的笑"},
           
        ]
    },
    {
        id: "9",
        songs: "特别的思念",
        name: "K_Williams",
        src: "music/特别的思念.mp3",
        alltime: "03:20",
        photo: "../img/chun2.png",
        lyrics: [
            {time: "00:04", lyric: "这样的夜 特别想念"},
            {time: "00:06", lyric: "远方的你 是否安睡"},
            {time: "00:11", lyric: "空的房间 你的照片"},
            {time: "00:16", lyric: "陪伴枕边 一起入眠"},
            {time: "00:18", lyric: "就这样一路相伴到今天"},
            {time: "00:23", lyric: "有一半时间却分隔两边"},
            {time: "00:29", lyric: "也想过这样对你不公平"},
            {time: "00:37", lyric: "可是那么爱怎么又分得开"},
            {time: "00:44", lyric: "这样的夜 特别想念"},
            {time: "00:47", lyric: "远方的你 是否安睡"},
            {time: "00:55", lyric: "空的房间 你的照片"},
            {time: "00:59", lyric: "陪伴枕边 一起入眠"},
            {time: "01:03", lyric: "就这样一路相伴到今天"},
            {time: "01:06", lyric: "有一半时间却分隔两边"},
            {time: "01:10", lyric: "也想过这样对你不公平"},
            {time: "01:14", lyric: "可是那么爱怎么又分得开"},
           
        ]
    },
    {
        id: "10",
        songs: "推脱",
        name: "梁芝芝",
        src: "music/推脱.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "沉默可以维持几秒钟"},
            {time: "00:20", lyric: "真情可以理智几分钟"},
            {time: "00:27", lyric: "每次犯错都是你在推脱"},
            {time: "00:33", lyric: "而我却扛上一身的痛"},
            {time: "00:40", lyric: "肩膀太窄天太高"},
            {time: "00:46", lyric: "责任太多时间太少"},
            {time: "00:53", lyric: "多想有人能帮我"},
            {time: "01:19", lyric: "把所有的烦忧都推脱"},
            {time: "01:26", lyric: "沉默可以维持几秒钟"},
            {time: "01:33", lyric: "真情可以理智几分钟"},
            {time: "01:39", lyric: "每次犯错都是你在推脱"},
            {time: "01:45", lyric: "而我却扛上一身的痛"},
            {time: "01:51", lyric: "肩膀太窄天太高"},
            {time: "01:57", lyric: "责任太多时间太少"},
            {time: "02:03", lyric: "多想有人能帮我"},
            {time: "02:10", lyric: "把所有的烦忧都推脱"},
          
        ]
    },
    {
        id: "11",
        songs: "刘美",
        name: "完美的结局",
        src: "music/完美的结局.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "我自己的生活 我自己把握"},
            {time: "00:20", lyric: "太多干涉  只会让我越错越多"},
            {time: "00:27", lyric: "我自己的生活 我自己选择"},
            {time: "00:33", lyric: "爱情和工作 不完美才是完美的依托"},
            {time: "00:40", lyric: "关起们来你说我抑郁"},
            {time: "00:46", lyric: "打开门你说我生性不羁"},
            {time: "00:53", lyric: "到底怎么才让你满意"},
            {time: "01:19", lyric: "还不如自己做自己"},
            {time: "01:26", lyric: "我自己的生活 我自己把握"},
            {time: "01:33", lyric: "太多的干涉  只会让我越错越多"},
            {time: "01:39", lyric: "我自己的生活 我自己选择"},
            {time: "01:45", lyric: "爱情和工作 不完美才是完美的依托"},
            {time: "01:51", lyric: "关起们来你说我抑郁"},
            {time: "01:57", lyric: "打开门你说我生性不羁"},
            {time: "02:03", lyric: "到底怎么才让你满意"},
            {time: "02:10", lyric: "还不如自己做自己"},
          
        ]
    },
    {
        id: "12",
        songs: "往事如烟",
        name: "许婉琳",
        src: "music/往事如烟.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "快到没节奏"},
            {time: "00:20", lyric: "相逢是缘分到了"},
            {time: "00:27", lyric: "离别是缘分不够"},
            {time: "00:33", lyric: "就这样逃走"},
            {time: "00:40", lyric: "快到没节奏"},
            {time: "00:46", lyric: "相逢是缘分到了"},
            {time: "00:53", lyric: "乌云遮住天"},
            {time: "01:19", lyric: "遮住了晴天"},
            {time: "01:26", lyric: "你迷了我的眼"},
            {time: "01:33", lyric: "看不见你的脸"},
            {time: "01:45", lyric: "往事已如烟"},
            {time: "01:52", lyric: "回忆在眼前"},
            {time: "02:04", lyric: "你从不挽留"},
            {time: "02:10", lyric: "我伸出的手"},
            {time: "02:17", lyric: "就这样逃走"},
            {time: "02:22", lyric: "快到没节奏"},
            {time: "02:45", lyric: "相逢是缘分到了"},
            {time: "05:52", lyric: "离别是缘分不够"},
            {time: "03:04", lyric: "就这样逃走"},
            {time: "03:10", lyric: "快到没节奏"},
            {time: "03:17", lyric: "相逢是缘分到了"},
            
        ]
    },
    {
        id: "13",
        songs: "忘不掉你的温度",
        name: "刘美",
        src: "music/忘不掉你的温度.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "我们分开好久了 "},
            {time: "00:20", lyric: "一直都神不守舍"},
            {time: "00:27", lyric: "回忆慢慢地模糊 "},
            {time: "00:33", lyric: "好像雨后的窗户"},
            {time: "00:40", lyric: "温柔永远留不住"},
            {time: "00:46", lyric: "却又忘不掉温度"},
            {time: "00:53", lyric: "以为自己走不出"},
            {time: "01:19", lyric: "这是一条死路"},
            {time: "01:26", lyric: "我不过只是你的玩物"},
            {time: "01:33", lyric: "我们分开好久了"},
            {time: "01:45", lyric: "一直都神不守舍"},
            {time: "01:52", lyric: "回忆慢慢地模糊 "},
            {time: "02:04", lyric: "好像雨后的窗户"},
            {time: "02:10", lyric: "温柔永远留不住"},
            {time: "02:17", lyric: "却又忘不掉温度"},
            {time: "02:22", lyric: "以为自己走不出"},
            {time: "02:45", lyric: "这是一条死路"},
            {time: "05:52", lyric: "我不过只是你的玩物"},
          
        ]
    },
    {
        id: "14",
        songs: "为你唱首歌",
        name: "刘美",
        src: "music/为你唱首歌.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "让我轻轻地为你唱首歌"},
            {time: "00:20", lyric: "唱出所有心事想对你说"},
            {time: "00:27", lyric: "这个世界 最爱的是你"},
            {time: "00:33", lyric: "请你用心聆听"},
            {time: "00:40", lyric: "为你唱这首歌 自己写的歌"},
            {time: "00:46", lyric: "每一段旋律 都是你和我"},
            {time: "00:53", lyric: "为你唱这首歌 也许不好听"},
            {time: "01:19", lyric: "只为了感谢 一路陪我的你"},
            {time: "01:26", lyric: "让我轻轻地为你唱首歌"},
            {time: "01:33", lyric: "唱出所有心事想对你说"},
            {time: "01:45", lyric: "这个世界 最爱的是你"},
            {time: "01:52", lyric: "请你用心聆听"},
            {time: "02:04", lyric: "为你唱这首歌 自己写的歌"},
            {time: "02:10", lyric: "每一段旋律 都是你和我"},
            {time: "02:17", lyric: "为你唱这首歌 也许不好听"},
            {time: "02:22", lyric: "只为了感谢 一路陪我的你"},
          
            
        ]
    },
    {
        id: "15",
        songs: "喜欢你",
        name: "刘美",
        src: "music/喜欢你.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "喜欢你 皱眉头 的样子"},
            {time: "00:20", lyric: "喜欢你 看着我 多专心"},
            {time: "00:27", lyric: "喜欢你 不要再 离开我"},
            {time: "00:33", lyric: "挽留你 如此的 喜欢你"},
            {time: "00:40", lyric: "想哭都是因为你不知道"},
            {time: "00:46", lyric: "想笑都是因为你多好"},
            {time: "00:53", lyric: "喜欢你 皱眉头 的样子"},
            {time: "01:19", lyric: "喜欢你 看着我 多专心"},
            {time: "01:26", lyric: "喜欢你 不要再 离开我"},
            {time: "01:33", lyric: "挽留你 如此的 喜欢你"},
            {time: "01:45", lyric: "想哭都是因为你不知道"},
            {time: "01:52", lyric: "想笑都是因为你多好"},
            
          
            
        ]
    },
    {
        id: "16",
        songs: "想你的夜晚",
        name: "刘美",
        src: "music/想你的夜晚.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "远处传来谁的歌声"},
            {time: "00:20", lyric: "在这夜深人静的时候"},
            {time: "00:27", lyric: "寂寞的声音让人好难过"},
            {time: "00:33", lyric: "又想了那时的你我"},
            {time: "00:40", lyric: "如果捂住了耳朵"},
            {time: "00:46", lyric: "然后挡住双眸"},
            {time: "00:53", lyric: "就可以停止脑中的回响"},
            {time: "01:19", lyric: "眼泪已婆娑"},
            {time: "01:26", lyric: "远处传来谁的歌声"},
            {time: "01:33", lyric: "在这夜深人静的时候"},
            {time: "01:45", lyric: "寂寞的声音让人好难过"},
            {time: "01:52", lyric: "又想了那时的你我"},
            {time: "02:04", lyric: "如果捂住了耳朵"},
            {time: "02:10", lyric: "然后挡住双眸"},
            {time: "02:17", lyric: "就可以停止脑中的回响"},
            {time: "02:22", lyric: "眼泪已婆娑"},
           
            
        ]
    }
    ,
    {
        id: "17",
        songs: "心的距离",
        name: "刘美",
        src: "music/心的距离.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "你为我采下一束花"},
            {time: "00:20", lyric: "你为我带在头上"},
            {time: "00:27", lyric: "吸引蝴蝶飞过来"},
            {time: "00:33", lyric: "我就好像公主一样"},
            {time: "00:40", lyric: "系上鞋带抬头对我笑"},
            {time: "00:46", lyric: "行人的羡慕眼神"},
            {time: "00:53", lyric: "让我觉得人生多完整"},
            {time: "01:19", lyric: "谢谢你给我那么美丽的时分"},
            {time: "01:26", lyric: "我会还给你更多的满分"},
            {time: "01:33", lyric: "依偎在你胸口的时候"},
            {time: "01:45", lyric: "感觉你心跳噗通声"},
            {time: "01:52", lyric: "你为我采下一束花"},
            {time: "02:04", lyric: "你为我带在头上"},
            {time: "02:10", lyric: "吸引蝴蝶飞过来"},
            {time: "02:17", lyric: "我就好像公主一样"},
            {time: "02:22", lyric: "你为我弯腰蹲下"},
            {time: "02:45", lyric: "系上鞋带抬头对我笑"},
            {time: "05:52", lyric: "行人的羡慕眼神"},
            {time: "03:04", lyric: "让我觉得人生多完整情缘不能再了"},
            {time: "03:10", lyric: "谢谢你给我那么美丽的时分"},
            {time: "03:17", lyric: "我会还给你更多的满分"},
            {time: "03:22", lyric: "爱有点痛会落空"},
            {time: "03:25", lyric: "依偎在你胸口的时候"},
            {time: "03:31", lyric: "感觉你心跳噗通声"},
            
        ]
    },
    {
        id: "18",
        songs: "幸福的味道",
        name: "刘美",
        src: "music/幸福的味道.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "小草带着春天的露水"},
            {time: "00:20", lyric: "加入行人前进的疲惫"},
            {time: "00:27", lyric: "路不管多远多长"},
            {time: "00:33", lyric: "只要向前就有方向"},
            {time: "00:40", lyric: "你的头上戴着花的香"},
            {time: "00:46", lyric: "手里牵着幸福的味道"},
            {time: "00:53", lyric: "未来不管多远多长"},
            {time: "01:19", lyric: "只要有你在身旁"},
            {time: "01:26", lyric: "那么多未完成的梦"},
            {time: "01:33", lyric: "那么多没吹过的风"},
            {time: "01:45", lyric: "小草带着春天的露水"},
            {time: "01:52", lyric: "加入行人前进的疲惫"},
            {time: "02:04", lyric: "路不管多远多长"},
            {time: "02:10", lyric: "只要向前就有方向"},
            {time: "02:17", lyric: "你的头上戴着花的香"},
            {time: "02:22", lyric: "手里牵着幸福的味道"},
            {time: "02:45", lyric: "未来不管多远多长"},
            {time: "05:52", lyric: "只要有你在身旁"},
            {time: "03:04", lyric: "那么多未完成的梦"},
            {time: "03:10", lyric: "那么多没吹过的风"},
            {time: "03:17", lyric: "你的头上戴着花的香"},
            {time: "03:22", lyric: "手里牵着幸福的味道"},
            {time: "03:25", lyric: "未来不管多远多长"},
            {time: "03:31", lyric: "只要有你在身旁"},
            {time: "03:37", lyric: "那么多未完成的梦"},
            {time: "03:42", lyric: "那么多没吹过的风"},
           
          
            
        ]
    },
    {
        id: "19",
        songs: "幸好有你",
        name: "刘美",
        src: "music/幸好有你.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "好幸运 有你的生命"},
            {time: "00:20", lyric: "陪伴我度过每个挫折"},
            {time: "00:27", lyric: "就算难过 又如何"},
            {time: "00:33", lyric: "如果没有你无论多快乐"},
            {time: "00:40", lyric: "所以未来要我们一起经过"},
            {time: "00:46", lyric: "所以付出一切都觉得值得"},
            {time: "00:53", lyric: "从来没有对彼此怀疑过"},
            {time: "01:19", lyric: "就是这样百分之百的生活"},
            {time: "01:26", lyric: "好幸运 有你的生命"},
            {time: "01:33", lyric: "陪伴我度过每个挫折"},
            {time: "01:45", lyric: "就算难过 又如何"},
            {time: "01:52", lyric: "如果没有你无论多快乐"},
            {time: "02:04", lyric: "所以未来要我们一起经过"},
            {time: "02:10", lyric: "所以付出一切都觉得值得"},
            {time: "02:17", lyric: "从来没有对彼此怀疑过"},
            {time: "02:22", lyric: "就是这样百分之百的生活"},
           
        ]
    },
    {
        id: "20",
        songs: "漩涡",
        name: "刘美",
        src: "music/漩涡.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "我掉进了漩涡"},
            {time: "00:20", lyric: "你种下的苦果"},
            {time: "00:27", lyric: "找不到出口"},
            {time: "00:33", lyric: "你却也不救我"},
            {time: "00:40", lyric: "像你的承诺"},
            {time: "00:46", lyric: "只会有开头"},
            {time: "00:53", lyric: "等不到结果"},
            {time: "01:19", lyric: "也没有歉疚"},
            {time: "01:26", lyric: "还不如就一头扎进了漩涡"},
            {time: "01:33", lyric: "求一个自由 一个人的自由"},
            {time: "01:45", lyric: "我掉进了漩涡"},
            {time: "01:52", lyric: "你种下的苦果"},
            {time: "02:04", lyric: "找不到出口"},
            {time: "02:10", lyric: "你却也不救我"},
            {time: "02:17", lyric: "像你的承诺"},
            {time: "02:22", lyric: "只会有开头"},
            {time: "02:45", lyric: "等不到结果"},
            {time: "05:52", lyric: "也没有歉疚"},
            {time: "03:04", lyric: "还不如就一头扎进了漩涡"},
            {time: "03:10", lyric: "求一个自由 一个人的自由"},
           
            
        ]
    },
    
]
